### ISSUE TITLE
Incorrect privacy.view status

### ISSUE THREAD

**Issue by shum16** [websemantics/vimeo-upload#10]
Please fix the value for private mode here:
'privacy.view': opts.private ? 'unlisted' : 'anybody' (line 165)

The correct value for private mode is 'nobody'.

P.s. thanks a lot for your plugin!

**Comment by websemantics** [comment]
Thanks @shum16 for the suggestion, 

Looking at [API valid privacy settings](https://developer.vimeo.com/api/endpoints/videos), it includes, `anybody`, `nobody`, `contacts`, `password`, `users`, `unlisted`, `disable`. 

It's probably nice to include all, but I see why it should be `nobody`, will make a change
