### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by JavedBoqo** [websemantics/vimeo-upload#8]
The video I tried to upload is successfully uploading but **onComplete** event i need to send email after successful uploading but unfortunately I am getting following error. Because of this error I can't get uploaded video url etc 
PATCH https://api.vimeo.com/videos/190425955 403 (Forbidden)

**Comment by JavedBoqo** [comment]
Well it was my mistake..I have not given upload access to my vimeo client ..

**Comment by Community-Tech** [comment]
Hi @JavedBoqo, hai have the same problema but i don't understand why. I already use a token with all scopes but nothing. Always the same error. Can you help me to understand?  Thanks
